name: "Build and deploy Github pages"

on:
  push:
    branches:
      - master

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: "Use Node 18"
        uses: actions/setup-node@v3
        with:
          node-version: 18

      
      - name: "Install dependencies"
        run: |
          yarn install

      - name: "Build"
        run: |
          yarn prod

      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public/
